services:
  backend:
    build: .
    ports:
      - "8080:8080"
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file: ".env"
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
